baseURL = "https://justinryanc.github.io/justinryanc.com-v1/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en"
defaultContentLanguage = "en"

title = "Justin Ryan Chambers"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Justin Ryan Chambers"
  headline = "Sr. IT Professional, Photographer"
  image = "me.png"  # path relative to static directory

  links = [
    # { email = "mailto:hello@your_domain.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
	# { 500px = { href = "https://500px.com/p/justinryanc", text = "500px" }},
    # { portfolio = { href = "https://justinryanc.myportfolio.com", text = "Portfolio", icon = "portfolio" }},
    { linkedin = "https://www.linkedin.com/in/justinryanc" },
    { flickr = "https://www.flickr.com/people/chambersjr/" },
    #{ youtube = "https://www.youtube.com/channel/UCIh7u81ip800JVw923yhSJw" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
